apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sql-update-kube
  name: sql-update-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sql-update-kube
  template:
    metadata:
      labels:
        run: sql-update-kube
    spec:
      nodeName: worker
      hostname: sql-update-kube
      containers:
        - name: sql-update-kube
          image: latonaio/sql-update-kube
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /var/lib/aion/Data
            - name: ui
              mountPath: /var/lib/aion/UI/sql-update-kube/public/
          env:
            - name : "RMQ_QUEUE_FROM"
              value: "sql-update-kube"
            - name : "RMQ_QUEUE_TO"
              value: "nestjs-data-connection-request-control-manager-consume"
            - name: "MYSQL_DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
      volumes:
        - name: data
          hostPath:
            path: /var/lib/aion/default/Data
        - name: ui
          hostPath:
            path: /var/lib/aion/UI/sql-update-kube/public/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sql-update-kube
  name: sql-update-kube
spec:
  selector:
    run: sql-update-kube
  type: ClusterIP
  ports:
    - name: dummy
      port: 40101
      protocol: TCP
      targetPort: 12345
