apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sql-update-kube
  name: sql-update-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sql-update-kube
  template:
    metadata:
      labels:
        run: sql-update-kube
    spec:
      nodeName: mysql-data
      hostname: sql-update-kube
      containers:
        - name: sql-update-kube
          image: latonaio/sql-update-kube
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /var/lib/aion/Data
            - name: ui
              mountPath: /var/lib/aion/UI/sql-update-kube/public/
          env:
            - name: RMQ_USER
              value: "XXXXXXXXXXX"
            - name: RMQ_PASS
              value: "XXXXXXXXXXX"
            - name: RMQ_ADDRESS
              value: "rabbitmq"
            - name: RMQ_PORT
              value: "5672"
            - name: RMQ_VHOST
              value: "sap"
            - name: RMQ_QUEUE_FROM
              value: "sql-update-kube"
            - name: RMQ_QUEUE_TO
              value: "sql-update-kube"
            - name: DB_USER
              value: "XXXXXXXXXXX"
            - name: DB_NAME
              value: "DataPlatformMastersAndTransactionsMysqlKube"
            - name: DB_PASS
              value: "XXXXXXXXXXX"
            - name: DB_ADDRESS
              value: "data-platform-masters-and-transactions-mysql-kube"
            - name: DB_PORT
              value: "3306"
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
      volumes:
        - name: data
          hostPath:
            path: /var/lib/aion/default/Data
        - name: ui
          hostPath:
            path: /var/lib/aion/UI/sql-update-kube/public/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sql-update-kube
  name: sql-update-kube
spec:
  selector:
    run: sql-update-kube
  type: ClusterIP
  ports:
    - name: dummy
      port: 40101
      protocol: TCP
      targetPort: 12345
