no-tests = true
output = "models"
wipe = true

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "XXXXXXXXXXX"
port = 30010
user = "XXXXXXXXXXX"
pass = "XXXXXXXXXXX"
sslmode = "false"
