no-tests = true
no-back-referencing = true
no-hooks = true
no-rows-affected = true
output = "models"
wipe = true

[mysql]
dbname = "DataPlatformMastersAndTransactionsMysqlKube"
host = "44.233.237.28"
port = 30010
user = "latona"
pass = "L@ton@2020!"
sslmode = "false"


