// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DataPlatformSupplyChainRelationshipDeliveryRelationDatum is an object representing the database table.
type DataPlatformSupplyChainRelationshipDeliveryRelationDatum struct {
	SupplyChainRelationshipID         int         `boil:"SupplyChainRelationshipID" json:"SupplyChainRelationshipID" toml:"SupplyChainRelationshipID" yaml:"SupplyChainRelationshipID"`
	SupplyChainRelationshipDeliveryID int         `boil:"SupplyChainRelationshipDeliveryID" json:"SupplyChainRelationshipDeliveryID" toml:"SupplyChainRelationshipDeliveryID" yaml:"SupplyChainRelationshipDeliveryID"`
	Buyer                             int         `boil:"Buyer" json:"Buyer" toml:"Buyer" yaml:"Buyer"`
	Seller                            int         `boil:"Seller" json:"Seller" toml:"Seller" yaml:"Seller"`
	DeliverToParty                    int         `boil:"DeliverToParty" json:"DeliverToParty" toml:"DeliverToParty" yaml:"DeliverToParty"`
	DeliverFromParty                  int         `boil:"DeliverFromParty" json:"DeliverFromParty" toml:"DeliverFromParty" yaml:"DeliverFromParty"`
	DefaultRelation                   null.Bool   `boil:"DefaultRelation" json:"DefaultRelation,omitempty" toml:"DefaultRelation" yaml:"DefaultRelation,omitempty"`
	CreationDate                      null.String `boil:"CreationDate" json:"CreationDate,omitempty" toml:"CreationDate" yaml:"CreationDate,omitempty"`
	LastChangeDate                    null.String `boil:"LastChangeDate" json:"LastChangeDate,omitempty" toml:"LastChangeDate" yaml:"LastChangeDate,omitempty"`
	IsMarkedForDeletion               null.Bool   `boil:"IsMarkedForDeletion" json:"IsMarkedForDeletion,omitempty" toml:"IsMarkedForDeletion" yaml:"IsMarkedForDeletion,omitempty"`

	R *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataPlatformSupplyChainRelationshipDeliveryRelationDatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataPlatformSupplyChainRelationshipDeliveryRelationDatumColumns = struct {
	SupplyChainRelationshipID         string
	SupplyChainRelationshipDeliveryID string
	Buyer                             string
	Seller                            string
	DeliverToParty                    string
	DeliverFromParty                  string
	DefaultRelation                   string
	CreationDate                      string
	LastChangeDate                    string
	IsMarkedForDeletion               string
}{
	SupplyChainRelationshipID:         "SupplyChainRelationshipID",
	SupplyChainRelationshipDeliveryID: "SupplyChainRelationshipDeliveryID",
	Buyer:                             "Buyer",
	Seller:                            "Seller",
	DeliverToParty:                    "DeliverToParty",
	DeliverFromParty:                  "DeliverFromParty",
	DefaultRelation:                   "DefaultRelation",
	CreationDate:                      "CreationDate",
	LastChangeDate:                    "LastChangeDate",
	IsMarkedForDeletion:               "IsMarkedForDeletion",
}

var DataPlatformSupplyChainRelationshipDeliveryRelationDatumTableColumns = struct {
	SupplyChainRelationshipID         string
	SupplyChainRelationshipDeliveryID string
	Buyer                             string
	Seller                            string
	DeliverToParty                    string
	DeliverFromParty                  string
	DefaultRelation                   string
	CreationDate                      string
	LastChangeDate                    string
	IsMarkedForDeletion               string
}{
	SupplyChainRelationshipID:         "data_platform_supply_chain_relationship_delivery_relation_data.SupplyChainRelationshipID",
	SupplyChainRelationshipDeliveryID: "data_platform_supply_chain_relationship_delivery_relation_data.SupplyChainRelationshipDeliveryID",
	Buyer:                             "data_platform_supply_chain_relationship_delivery_relation_data.Buyer",
	Seller:                            "data_platform_supply_chain_relationship_delivery_relation_data.Seller",
	DeliverToParty:                    "data_platform_supply_chain_relationship_delivery_relation_data.DeliverToParty",
	DeliverFromParty:                  "data_platform_supply_chain_relationship_delivery_relation_data.DeliverFromParty",
	DefaultRelation:                   "data_platform_supply_chain_relationship_delivery_relation_data.DefaultRelation",
	CreationDate:                      "data_platform_supply_chain_relationship_delivery_relation_data.CreationDate",
	LastChangeDate:                    "data_platform_supply_chain_relationship_delivery_relation_data.LastChangeDate",
	IsMarkedForDeletion:               "data_platform_supply_chain_relationship_delivery_relation_data.IsMarkedForDeletion",
}

// Generated where

var DataPlatformSupplyChainRelationshipDeliveryRelationDatumWhere = struct {
	SupplyChainRelationshipID         whereHelperint
	SupplyChainRelationshipDeliveryID whereHelperint
	Buyer                             whereHelperint
	Seller                            whereHelperint
	DeliverToParty                    whereHelperint
	DeliverFromParty                  whereHelperint
	DefaultRelation                   whereHelpernull_Bool
	CreationDate                      whereHelpernull_String
	LastChangeDate                    whereHelpernull_String
	IsMarkedForDeletion               whereHelpernull_Bool
}{
	SupplyChainRelationshipID:         whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`SupplyChainRelationshipID`"},
	SupplyChainRelationshipDeliveryID: whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`SupplyChainRelationshipDeliveryID`"},
	Buyer:                             whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`Buyer`"},
	Seller:                            whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`Seller`"},
	DeliverToParty:                    whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`DeliverToParty`"},
	DeliverFromParty:                  whereHelperint{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`DeliverFromParty`"},
	DefaultRelation:                   whereHelpernull_Bool{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`DefaultRelation`"},
	CreationDate:                      whereHelpernull_String{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`CreationDate`"},
	LastChangeDate:                    whereHelpernull_String{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`LastChangeDate`"},
	IsMarkedForDeletion:               whereHelpernull_Bool{field: "`data_platform_supply_chain_relationship_delivery_relation_data`.`IsMarkedForDeletion`"},
}

// DataPlatformSupplyChainRelationshipDeliveryRelationDatumRels is where relationship names are stored.
var DataPlatformSupplyChainRelationshipDeliveryRelationDatumRels = struct {
	BuyerDataPlatformSupplyChainRelationshipGeneralDatum    string
	BuyerDataPlatformBillOfMaterialHeaderData               string
	ComponentProductBuyerDataPlatformBillOfMaterialItemData string
	BuyerDataPlatformDeliveryDocumentHeaderData             string
	BuyerDataPlatformDeliveryDocumentItemData               string
	BuyerDataPlatformOperationsHeaderData                   string
	BuyerDataPlatformOperationsItemData                     string
}{
	BuyerDataPlatformSupplyChainRelationshipGeneralDatum:    "BuyerDataPlatformSupplyChainRelationshipGeneralDatum",
	BuyerDataPlatformBillOfMaterialHeaderData:               "BuyerDataPlatformBillOfMaterialHeaderData",
	ComponentProductBuyerDataPlatformBillOfMaterialItemData: "ComponentProductBuyerDataPlatformBillOfMaterialItemData",
	BuyerDataPlatformDeliveryDocumentHeaderData:             "BuyerDataPlatformDeliveryDocumentHeaderData",
	BuyerDataPlatformDeliveryDocumentItemData:               "BuyerDataPlatformDeliveryDocumentItemData",
	BuyerDataPlatformOperationsHeaderData:                   "BuyerDataPlatformOperationsHeaderData",
	BuyerDataPlatformOperationsItemData:                     "BuyerDataPlatformOperationsItemData",
}

// dataPlatformSupplyChainRelationshipDeliveryRelationDatumR is where relationships are stored.
type dataPlatformSupplyChainRelationshipDeliveryRelationDatumR struct {
	BuyerDataPlatformSupplyChainRelationshipGeneralDatum    *DataPlatformSupplyChainRelationshipGeneralDatum `boil:"BuyerDataPlatformSupplyChainRelationshipGeneralDatum" json:"BuyerDataPlatformSupplyChainRelationshipGeneralDatum" toml:"BuyerDataPlatformSupplyChainRelationshipGeneralDatum" yaml:"BuyerDataPlatformSupplyChainRelationshipGeneralDatum"`
	BuyerDataPlatformBillOfMaterialHeaderData               DataPlatformBillOfMaterialHeaderDatumSlice       `boil:"BuyerDataPlatformBillOfMaterialHeaderData" json:"BuyerDataPlatformBillOfMaterialHeaderData" toml:"BuyerDataPlatformBillOfMaterialHeaderData" yaml:"BuyerDataPlatformBillOfMaterialHeaderData"`
	ComponentProductBuyerDataPlatformBillOfMaterialItemData DataPlatformBillOfMaterialItemDatumSlice         `boil:"ComponentProductBuyerDataPlatformBillOfMaterialItemData" json:"ComponentProductBuyerDataPlatformBillOfMaterialItemData" toml:"ComponentProductBuyerDataPlatformBillOfMaterialItemData" yaml:"ComponentProductBuyerDataPlatformBillOfMaterialItemData"`
	BuyerDataPlatformDeliveryDocumentHeaderData             DataPlatformDeliveryDocumentHeaderDatumSlice     `boil:"BuyerDataPlatformDeliveryDocumentHeaderData" json:"BuyerDataPlatformDeliveryDocumentHeaderData" toml:"BuyerDataPlatformDeliveryDocumentHeaderData" yaml:"BuyerDataPlatformDeliveryDocumentHeaderData"`
	BuyerDataPlatformDeliveryDocumentItemData               DataPlatformDeliveryDocumentItemDatumSlice       `boil:"BuyerDataPlatformDeliveryDocumentItemData" json:"BuyerDataPlatformDeliveryDocumentItemData" toml:"BuyerDataPlatformDeliveryDocumentItemData" yaml:"BuyerDataPlatformDeliveryDocumentItemData"`
	BuyerDataPlatformOperationsHeaderData                   DataPlatformOperationsHeaderDatumSlice           `boil:"BuyerDataPlatformOperationsHeaderData" json:"BuyerDataPlatformOperationsHeaderData" toml:"BuyerDataPlatformOperationsHeaderData" yaml:"BuyerDataPlatformOperationsHeaderData"`
	BuyerDataPlatformOperationsItemData                     DataPlatformOperationsItemDatumSlice             `boil:"BuyerDataPlatformOperationsItemData" json:"BuyerDataPlatformOperationsItemData" toml:"BuyerDataPlatformOperationsItemData" yaml:"BuyerDataPlatformOperationsItemData"`
}

// NewStruct creates a new relationship struct
func (*dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) NewStruct() *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR {
	return &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformSupplyChainRelationshipGeneralDatum() *DataPlatformSupplyChainRelationshipGeneralDatum {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformSupplyChainRelationshipGeneralDatum
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformBillOfMaterialHeaderData() DataPlatformBillOfMaterialHeaderDatumSlice {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformBillOfMaterialHeaderData
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetComponentProductBuyerDataPlatformBillOfMaterialItemData() DataPlatformBillOfMaterialItemDatumSlice {
	if r == nil {
		return nil
	}
	return r.ComponentProductBuyerDataPlatformBillOfMaterialItemData
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformDeliveryDocumentHeaderData() DataPlatformDeliveryDocumentHeaderDatumSlice {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformDeliveryDocumentHeaderData
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformDeliveryDocumentItemData() DataPlatformDeliveryDocumentItemDatumSlice {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformDeliveryDocumentItemData
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformOperationsHeaderData() DataPlatformOperationsHeaderDatumSlice {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformOperationsHeaderData
}

func (r *dataPlatformSupplyChainRelationshipDeliveryRelationDatumR) GetBuyerDataPlatformOperationsItemData() DataPlatformOperationsItemDatumSlice {
	if r == nil {
		return nil
	}
	return r.BuyerDataPlatformOperationsItemData
}

// dataPlatformSupplyChainRelationshipDeliveryRelationDatumL is where Load methods for each relationship are stored.
type dataPlatformSupplyChainRelationshipDeliveryRelationDatumL struct{}

var (
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumAllColumns            = []string{"SupplyChainRelationshipID", "SupplyChainRelationshipDeliveryID", "Buyer", "Seller", "DeliverToParty", "DeliverFromParty", "DefaultRelation", "CreationDate", "LastChangeDate", "IsMarkedForDeletion"}
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithoutDefault = []string{"SupplyChainRelationshipID", "SupplyChainRelationshipDeliveryID", "Buyer", "Seller", "DeliverToParty", "DeliverFromParty", "DefaultRelation", "CreationDate", "LastChangeDate", "IsMarkedForDeletion"}
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithDefault    = []string{}
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns     = []string{"SupplyChainRelationshipID", "SupplyChainRelationshipDeliveryID", "Buyer", "Seller", "DeliverToParty", "DeliverFromParty"}
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumGeneratedColumns      = []string{}
)

type (
	// DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice is an alias for a slice of pointers to DataPlatformSupplyChainRelationshipDeliveryRelationDatum.
	// This should almost always be used instead of []DataPlatformSupplyChainRelationshipDeliveryRelationDatum.
	DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumType                 = reflect.TypeOf(&DataPlatformSupplyChainRelationshipDeliveryRelationDatum{})
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping              = queries.MakeStructMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyMapping, _ = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCacheMut       sync.RWMutex
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCache          = make(map[string]insertCache)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCacheMut       sync.RWMutex
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCache          = make(map[string]updateCache)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCacheMut       sync.RWMutex
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single dataPlatformSupplyChainRelationshipDeliveryRelationDatum record from the query.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataPlatformSupplyChainRelationshipDeliveryRelationDatum, error) {
	o := &DataPlatformSupplyChainRelationshipDeliveryRelationDatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for data_platform_supply_chain_relationship_delivery_relation_data")
	}

	return o, nil
}

// All returns all DataPlatformSupplyChainRelationshipDeliveryRelationDatum records from the query.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice, error) {
	var o []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DataPlatformSupplyChainRelationshipDeliveryRelationDatum slice")
	}

	return o, nil
}

// Count returns the count of all DataPlatformSupplyChainRelationshipDeliveryRelationDatum records in the query.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count data_platform_supply_chain_relationship_delivery_relation_data rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if data_platform_supply_chain_relationship_delivery_relation_data exists")
	}

	return count > 0, nil
}

// BuyerDataPlatformSupplyChainRelationshipGeneralDatum pointed to by the foreign key.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformSupplyChainRelationshipGeneralDatum(mods ...qm.QueryMod) dataPlatformSupplyChainRelationshipGeneralDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`Buyer` = ?", o.Buyer),
	}

	queryMods = append(queryMods, mods...)

	return DataPlatformSupplyChainRelationshipGeneralData(queryMods...)
}

// BuyerDataPlatformBillOfMaterialHeaderData retrieves all the data_platform_bill_of_material_header_datum's DataPlatformBillOfMaterialHeaderData with an executor via Buyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformBillOfMaterialHeaderData(mods ...qm.QueryMod) dataPlatformBillOfMaterialHeaderDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_bill_of_material_header_data`.`Buyer`=?", o.Buyer),
	)

	return DataPlatformBillOfMaterialHeaderData(queryMods...)
}

// ComponentProductBuyerDataPlatformBillOfMaterialItemData retrieves all the data_platform_bill_of_material_item_datum's DataPlatformBillOfMaterialItemData with an executor via ComponentProductBuyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) ComponentProductBuyerDataPlatformBillOfMaterialItemData(mods ...qm.QueryMod) dataPlatformBillOfMaterialItemDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_bill_of_material_item_data`.`ComponentProductBuyer`=?", o.Buyer),
	)

	return DataPlatformBillOfMaterialItemData(queryMods...)
}

// BuyerDataPlatformDeliveryDocumentHeaderData retrieves all the data_platform_delivery_document_header_datum's DataPlatformDeliveryDocumentHeaderData with an executor via Buyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformDeliveryDocumentHeaderData(mods ...qm.QueryMod) dataPlatformDeliveryDocumentHeaderDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_delivery_document_header_data`.`Buyer`=?", o.Buyer),
	)

	return DataPlatformDeliveryDocumentHeaderData(queryMods...)
}

// BuyerDataPlatformDeliveryDocumentItemData retrieves all the data_platform_delivery_document_item_datum's DataPlatformDeliveryDocumentItemData with an executor via Buyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformDeliveryDocumentItemData(mods ...qm.QueryMod) dataPlatformDeliveryDocumentItemDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_delivery_document_item_data`.`Buyer`=?", o.Buyer),
	)

	return DataPlatformDeliveryDocumentItemData(queryMods...)
}

// BuyerDataPlatformOperationsHeaderData retrieves all the data_platform_operations_header_datum's DataPlatformOperationsHeaderData with an executor via Buyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformOperationsHeaderData(mods ...qm.QueryMod) dataPlatformOperationsHeaderDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_operations_header_data`.`Buyer`=?", o.Buyer),
	)

	return DataPlatformOperationsHeaderData(queryMods...)
}

// BuyerDataPlatformOperationsItemData retrieves all the data_platform_operations_item_datum's DataPlatformOperationsItemData with an executor via Buyer column.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) BuyerDataPlatformOperationsItemData(mods ...qm.QueryMod) dataPlatformOperationsItemDatumQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`data_platform_operations_item_data`.`Buyer`=?", o.Buyer),
	)

	return DataPlatformOperationsItemData(queryMods...)
}

// LoadBuyerDataPlatformSupplyChainRelationshipGeneralDatum allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformSupplyChainRelationshipGeneralDatum(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_supply_chain_relationship_general_data`),
		qm.WhereIn(`data_platform_supply_chain_relationship_general_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataPlatformSupplyChainRelationshipGeneralDatum")
	}

	var resultSlice []*DataPlatformSupplyChainRelationshipGeneralDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataPlatformSupplyChainRelationshipGeneralDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_platform_supply_chain_relationship_general_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_supply_chain_relationship_general_data")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.BuyerDataPlatformSupplyChainRelationshipGeneralDatum = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformSupplyChainRelationshipGeneralDatum = foreign
				break
			}
		}
	}

	return nil
}

// LoadBuyerDataPlatformBillOfMaterialHeaderData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformBillOfMaterialHeaderData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_bill_of_material_header_data`),
		qm.WhereIn(`data_platform_bill_of_material_header_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_bill_of_material_header_data")
	}

	var resultSlice []*DataPlatformBillOfMaterialHeaderDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_bill_of_material_header_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_bill_of_material_header_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_bill_of_material_header_data")
	}

	if singular {
		object.R.BuyerDataPlatformBillOfMaterialHeaderData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformBillOfMaterialHeaderData = append(local.R.BuyerDataPlatformBillOfMaterialHeaderData, foreign)
				break
			}
		}
	}

	return nil
}

// LoadComponentProductBuyerDataPlatformBillOfMaterialItemData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadComponentProductBuyerDataPlatformBillOfMaterialItemData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_bill_of_material_item_data`),
		qm.WhereIn(`data_platform_bill_of_material_item_data.ComponentProductBuyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_bill_of_material_item_data")
	}

	var resultSlice []*DataPlatformBillOfMaterialItemDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_bill_of_material_item_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_bill_of_material_item_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_bill_of_material_item_data")
	}

	if singular {
		object.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.ComponentProductBuyer {
				local.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData = append(local.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData, foreign)
				break
			}
		}
	}

	return nil
}

// LoadBuyerDataPlatformDeliveryDocumentHeaderData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformDeliveryDocumentHeaderData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_delivery_document_header_data`),
		qm.WhereIn(`data_platform_delivery_document_header_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_delivery_document_header_data")
	}

	var resultSlice []*DataPlatformDeliveryDocumentHeaderDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_delivery_document_header_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_delivery_document_header_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_delivery_document_header_data")
	}

	if singular {
		object.R.BuyerDataPlatformDeliveryDocumentHeaderData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformDeliveryDocumentHeaderData = append(local.R.BuyerDataPlatformDeliveryDocumentHeaderData, foreign)
				break
			}
		}
	}

	return nil
}

// LoadBuyerDataPlatformDeliveryDocumentItemData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformDeliveryDocumentItemData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_delivery_document_item_data`),
		qm.WhereIn(`data_platform_delivery_document_item_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_delivery_document_item_data")
	}

	var resultSlice []*DataPlatformDeliveryDocumentItemDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_delivery_document_item_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_delivery_document_item_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_delivery_document_item_data")
	}

	if singular {
		object.R.BuyerDataPlatformDeliveryDocumentItemData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformDeliveryDocumentItemData = append(local.R.BuyerDataPlatformDeliveryDocumentItemData, foreign)
				break
			}
		}
	}

	return nil
}

// LoadBuyerDataPlatformOperationsHeaderData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformOperationsHeaderData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_operations_header_data`),
		qm.WhereIn(`data_platform_operations_header_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_operations_header_data")
	}

	var resultSlice []*DataPlatformOperationsHeaderDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_operations_header_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_operations_header_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_operations_header_data")
	}

	if singular {
		object.R.BuyerDataPlatformOperationsHeaderData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformOperationsHeaderData = append(local.R.BuyerDataPlatformOperationsHeaderData, foreign)
				break
			}
		}
	}

	return nil
}

// LoadBuyerDataPlatformOperationsItemData allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (dataPlatformSupplyChainRelationshipDeliveryRelationDatumL) LoadBuyerDataPlatformOperationsItemData(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformSupplyChainRelationshipDeliveryRelationDatum
	var object *DataPlatformSupplyChainRelationshipDeliveryRelationDatum

	if singular {
		var ok bool
		object, ok = maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if !ok {
			object = new(DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	} else {
		s, ok := maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum.(*[]*DataPlatformSupplyChainRelationshipDeliveryRelationDatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformSupplyChainRelationshipDeliveryRelationDatum))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
		}
		args = append(args, object.Buyer)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{}
			}

			for _, a := range args {
				if a == obj.Buyer {
					continue Outer
				}
			}

			args = append(args, obj.Buyer)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_operations_item_data`),
		qm.WhereIn(`data_platform_operations_item_data.Buyer in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load data_platform_operations_item_data")
	}

	var resultSlice []*DataPlatformOperationsItemDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice data_platform_operations_item_data")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on data_platform_operations_item_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_operations_item_data")
	}

	if singular {
		object.R.BuyerDataPlatformOperationsItemData = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.Buyer == foreign.Buyer {
				local.R.BuyerDataPlatformOperationsItemData = append(local.R.BuyerDataPlatformOperationsItemData, foreign)
				break
			}
		}
	}

	return nil
}

// SetBuyerDataPlatformSupplyChainRelationshipGeneralDatum of the dataPlatformSupplyChainRelationshipDeliveryRelationDatum to the related item.
// Sets o.R.BuyerDataPlatformSupplyChainRelationshipGeneralDatum to related.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) SetBuyerDataPlatformSupplyChainRelationshipGeneralDatum(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataPlatformSupplyChainRelationshipGeneralDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `data_platform_supply_chain_relationship_delivery_relation_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
		strmangle.WhereClause("`", "`", 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns),
	)
	values := []interface{}{related.Buyer, o.SupplyChainRelationshipID, o.SupplyChainRelationshipDeliveryID, o.Buyer, o.Seller, o.DeliverToParty, o.DeliverFromParty}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.Buyer = related.Buyer
	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformSupplyChainRelationshipGeneralDatum: related,
		}
	} else {
		o.R.BuyerDataPlatformSupplyChainRelationshipGeneralDatum = related
	}

	return nil
}

// AddBuyerDataPlatformBillOfMaterialHeaderData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.BuyerDataPlatformBillOfMaterialHeaderData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddBuyerDataPlatformBillOfMaterialHeaderData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformBillOfMaterialHeaderDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Buyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_bill_of_material_header_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformBillOfMaterialHeaderDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.BillOfMaterial}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Buyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformBillOfMaterialHeaderData: related,
		}
	} else {
		o.R.BuyerDataPlatformBillOfMaterialHeaderData = append(o.R.BuyerDataPlatformBillOfMaterialHeaderData, related...)
	}

	return nil
}

// AddComponentProductBuyerDataPlatformBillOfMaterialItemData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddComponentProductBuyerDataPlatformBillOfMaterialItemData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformBillOfMaterialItemDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.ComponentProductBuyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_bill_of_material_item_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"ComponentProductBuyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformBillOfMaterialItemDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.BillOfMaterial, rel.BillOfMaterialItem}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.ComponentProductBuyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			ComponentProductBuyerDataPlatformBillOfMaterialItemData: related,
		}
	} else {
		o.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData = append(o.R.ComponentProductBuyerDataPlatformBillOfMaterialItemData, related...)
	}

	return nil
}

// AddBuyerDataPlatformDeliveryDocumentHeaderData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.BuyerDataPlatformDeliveryDocumentHeaderData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddBuyerDataPlatformDeliveryDocumentHeaderData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformDeliveryDocumentHeaderDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Buyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_delivery_document_header_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformDeliveryDocumentHeaderDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.DeliveryDocument}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Buyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformDeliveryDocumentHeaderData: related,
		}
	} else {
		o.R.BuyerDataPlatformDeliveryDocumentHeaderData = append(o.R.BuyerDataPlatformDeliveryDocumentHeaderData, related...)
	}

	return nil
}

// AddBuyerDataPlatformDeliveryDocumentItemData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.BuyerDataPlatformDeliveryDocumentItemData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddBuyerDataPlatformDeliveryDocumentItemData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformDeliveryDocumentItemDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Buyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_delivery_document_item_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformDeliveryDocumentItemDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.DeliveryDocument, rel.DeliveryDocumentItem}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Buyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformDeliveryDocumentItemData: related,
		}
	} else {
		o.R.BuyerDataPlatformDeliveryDocumentItemData = append(o.R.BuyerDataPlatformDeliveryDocumentItemData, related...)
	}

	return nil
}

// AddBuyerDataPlatformOperationsHeaderData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.BuyerDataPlatformOperationsHeaderData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddBuyerDataPlatformOperationsHeaderData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformOperationsHeaderDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Buyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_operations_header_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformOperationsHeaderDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.Operations}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Buyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformOperationsHeaderData: related,
		}
	} else {
		o.R.BuyerDataPlatformOperationsHeaderData = append(o.R.BuyerDataPlatformOperationsHeaderData, related...)
	}

	return nil
}

// AddBuyerDataPlatformOperationsItemData adds the given related objects to the existing relationships
// of the data_platform_supply_chain_relationship_delivery_relation_datum, optionally inserting them as new records.
// Appends related to o.R.BuyerDataPlatformOperationsItemData.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) AddBuyerDataPlatformOperationsItemData(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DataPlatformOperationsItemDatum) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.Buyer = o.Buyer
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `data_platform_operations_item_data` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"Buyer"}),
				strmangle.WhereClause("`", "`", 0, dataPlatformOperationsItemDatumPrimaryKeyColumns),
			)
			values := []interface{}{o.Buyer, rel.Operations, rel.OperationsItem}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.Buyer = o.Buyer
		}
	}

	if o.R == nil {
		o.R = &dataPlatformSupplyChainRelationshipDeliveryRelationDatumR{
			BuyerDataPlatformOperationsItemData: related,
		}
	} else {
		o.R.BuyerDataPlatformOperationsItemData = append(o.R.BuyerDataPlatformOperationsItemData, related...)
	}

	return nil
}

// DataPlatformSupplyChainRelationshipDeliveryRelationData retrieves all the records using an executor.
func DataPlatformSupplyChainRelationshipDeliveryRelationData(mods ...qm.QueryMod) dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery {
	mods = append(mods, qm.From("`data_platform_supply_chain_relationship_delivery_relation_data`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_platform_supply_chain_relationship_delivery_relation_data`.*"})
	}

	return dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery{q}
}

// FindDataPlatformSupplyChainRelationshipDeliveryRelationDatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataPlatformSupplyChainRelationshipDeliveryRelationDatum(ctx context.Context, exec boil.ContextExecutor, supplyChainRelationshipID int, supplyChainRelationshipDeliveryID int, buyer int, seller int, deliverToParty int, deliverFromParty int, selectCols ...string) (*DataPlatformSupplyChainRelationshipDeliveryRelationDatum, error) {
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumObj := &DataPlatformSupplyChainRelationshipDeliveryRelationDatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_platform_supply_chain_relationship_delivery_relation_data` where `SupplyChainRelationshipID`=? AND `SupplyChainRelationshipDeliveryID`=? AND `Buyer`=? AND `Seller`=? AND `DeliverToParty`=? AND `DeliverFromParty`=?", sel,
	)

	q := queries.Raw(query, supplyChainRelationshipID, supplyChainRelationshipDeliveryID, buyer, seller, deliverToParty, deliverFromParty)

	err := q.Bind(ctx, exec, dataPlatformSupplyChainRelationshipDeliveryRelationDatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from data_platform_supply_chain_relationship_delivery_relation_data")
	}

	return dataPlatformSupplyChainRelationshipDeliveryRelationDatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no data_platform_supply_chain_relationship_delivery_relation_data provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCacheMut.RLock()
	cache, cached := dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCache[key]
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumAllColumns,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithDefault,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_platform_supply_chain_relationship_delivery_relation_data` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_platform_supply_chain_relationship_delivery_relation_data` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_platform_supply_chain_relationship_delivery_relation_data` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into data_platform_supply_chain_relationship_delivery_relation_data")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.SupplyChainRelationshipID,
		o.SupplyChainRelationshipDeliveryID,
		o.Buyer,
		o.Seller,
		o.DeliverToParty,
		o.DeliverFromParty,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for data_platform_supply_chain_relationship_delivery_relation_data")
	}

CacheNoHooks:
	if !cached {
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCacheMut.Lock()
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCache[key] = cache
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DataPlatformSupplyChainRelationshipDeliveryRelationDatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	var err error
	key := makeCacheKey(columns, nil)
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCacheMut.RLock()
	cache, cached := dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCache[key]
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumAllColumns,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update data_platform_supply_chain_relationship_delivery_relation_data, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_platform_supply_chain_relationship_delivery_relation_data` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, append(wl, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update data_platform_supply_chain_relationship_delivery_relation_data row")
	}

	if !cached {
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCacheMut.Lock()
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCache[key] = cache
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for data_platform_supply_chain_relationship_delivery_relation_data")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_platform_supply_chain_relationship_delivery_relation_data` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in dataPlatformSupplyChainRelationshipDeliveryRelationDatum slice")
	}

	return nil
}

var mySQLDataPlatformSupplyChainRelationshipDeliveryRelationDatumUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no data_platform_supply_chain_relationship_delivery_relation_data provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataPlatformSupplyChainRelationshipDeliveryRelationDatumUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCacheMut.RLock()
	cache, cached := dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCache[key]
	dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumAllColumns,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithDefault,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumAllColumns,
			dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert data_platform_supply_chain_relationship_delivery_relation_data, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`data_platform_supply_chain_relationship_delivery_relation_data`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_platform_supply_chain_relationship_delivery_relation_data` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for data_platform_supply_chain_relationship_delivery_relation_data")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataPlatformSupplyChainRelationshipDeliveryRelationDatumType, dataPlatformSupplyChainRelationshipDeliveryRelationDatumMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for data_platform_supply_chain_relationship_delivery_relation_data")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for data_platform_supply_chain_relationship_delivery_relation_data")
	}

CacheNoHooks:
	if !cached {
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCacheMut.Lock()
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCache[key] = cache
		dataPlatformSupplyChainRelationshipDeliveryRelationDatumUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DataPlatformSupplyChainRelationshipDeliveryRelationDatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no DataPlatformSupplyChainRelationshipDeliveryRelationDatum provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyMapping)
	sql := "DELETE FROM `data_platform_supply_chain_relationship_delivery_relation_data` WHERE `SupplyChainRelationshipID`=? AND `SupplyChainRelationshipDeliveryID`=? AND `Buyer`=? AND `Seller`=? AND `DeliverToParty`=? AND `DeliverFromParty`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from data_platform_supply_chain_relationship_delivery_relation_data")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no dataPlatformSupplyChainRelationshipDeliveryRelationDatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from data_platform_supply_chain_relationship_delivery_relation_data")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_platform_supply_chain_relationship_delivery_relation_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from dataPlatformSupplyChainRelationshipDeliveryRelationDatum slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataPlatformSupplyChainRelationshipDeliveryRelationDatum(ctx, exec, o.SupplyChainRelationshipID, o.SupplyChainRelationshipDeliveryID, o.Buyer, o.Seller, o.DeliverToParty, o.DeliverFromParty)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_platform_supply_chain_relationship_delivery_relation_data`.* FROM `data_platform_supply_chain_relationship_delivery_relation_data` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformSupplyChainRelationshipDeliveryRelationDatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DataPlatformSupplyChainRelationshipDeliveryRelationDatumSlice")
	}

	*o = slice

	return nil
}

// DataPlatformSupplyChainRelationshipDeliveryRelationDatumExists checks if the DataPlatformSupplyChainRelationshipDeliveryRelationDatum row exists.
func DataPlatformSupplyChainRelationshipDeliveryRelationDatumExists(ctx context.Context, exec boil.ContextExecutor, supplyChainRelationshipID int, supplyChainRelationshipDeliveryID int, buyer int, seller int, deliverToParty int, deliverFromParty int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_platform_supply_chain_relationship_delivery_relation_data` where `SupplyChainRelationshipID`=? AND `SupplyChainRelationshipDeliveryID`=? AND `Buyer`=? AND `Seller`=? AND `DeliverToParty`=? AND `DeliverFromParty`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, supplyChainRelationshipID, supplyChainRelationshipDeliveryID, buyer, seller, deliverToParty, deliverFromParty)
	}
	row := exec.QueryRowContext(ctx, sql, supplyChainRelationshipID, supplyChainRelationshipDeliveryID, buyer, seller, deliverToParty, deliverFromParty)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if data_platform_supply_chain_relationship_delivery_relation_data exists")
	}

	return exists, nil
}

// Exists checks if the DataPlatformSupplyChainRelationshipDeliveryRelationDatum row exists.
func (o *DataPlatformSupplyChainRelationshipDeliveryRelationDatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataPlatformSupplyChainRelationshipDeliveryRelationDatumExists(ctx, exec, o.SupplyChainRelationshipID, o.SupplyChainRelationshipDeliveryID, o.Buyer, o.Seller, o.DeliverToParty, o.DeliverFromParty)
}
