// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// DataPlatformProductStockByBatchDataOld is an object representing the database table.
type DataPlatformProductStockByBatchDataOld struct {
	BusinessPartner           int         `boil:"BusinessPartner" json:"BusinessPartner" toml:"BusinessPartner" yaml:"BusinessPartner"`
	Product                   string      `boil:"Product" json:"Product" toml:"Product" yaml:"Product"`
	Plant                     string      `boil:"Plant" json:"Plant" toml:"Plant" yaml:"Plant"`
	Batch                     string      `boil:"Batch" json:"Batch" toml:"Batch" yaml:"Batch"`
	InventoryStockType        null.String `boil:"InventoryStockType" json:"InventoryStockType,omitempty" toml:"InventoryStockType" yaml:"InventoryStockType,omitempty"`
	InventorySpecialStockType null.String `boil:"InventorySpecialStockType" json:"InventorySpecialStockType,omitempty" toml:"InventorySpecialStockType" yaml:"InventorySpecialStockType,omitempty"`
	ProductStock              float32     `boil:"ProductStock" json:"ProductStock" toml:"ProductStock" yaml:"ProductStock"`

	R *dataPlatformProductStockByBatchDataOldR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L dataPlatformProductStockByBatchDataOldL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DataPlatformProductStockByBatchDataOldColumns = struct {
	BusinessPartner           string
	Product                   string
	Plant                     string
	Batch                     string
	InventoryStockType        string
	InventorySpecialStockType string
	ProductStock              string
}{
	BusinessPartner:           "BusinessPartner",
	Product:                   "Product",
	Plant:                     "Plant",
	Batch:                     "Batch",
	InventoryStockType:        "InventoryStockType",
	InventorySpecialStockType: "InventorySpecialStockType",
	ProductStock:              "ProductStock",
}

var DataPlatformProductStockByBatchDataOldTableColumns = struct {
	BusinessPartner           string
	Product                   string
	Plant                     string
	Batch                     string
	InventoryStockType        string
	InventorySpecialStockType string
	ProductStock              string
}{
	BusinessPartner:           "data_platform_product_stock_by_batch_data_old.BusinessPartner",
	Product:                   "data_platform_product_stock_by_batch_data_old.Product",
	Plant:                     "data_platform_product_stock_by_batch_data_old.Plant",
	Batch:                     "data_platform_product_stock_by_batch_data_old.Batch",
	InventoryStockType:        "data_platform_product_stock_by_batch_data_old.InventoryStockType",
	InventorySpecialStockType: "data_platform_product_stock_by_batch_data_old.InventorySpecialStockType",
	ProductStock:              "data_platform_product_stock_by_batch_data_old.ProductStock",
}

// Generated where

var DataPlatformProductStockByBatchDataOldWhere = struct {
	BusinessPartner           whereHelperint
	Product                   whereHelperstring
	Plant                     whereHelperstring
	Batch                     whereHelperstring
	InventoryStockType        whereHelpernull_String
	InventorySpecialStockType whereHelpernull_String
	ProductStock              whereHelperfloat32
}{
	BusinessPartner:           whereHelperint{field: "`data_platform_product_stock_by_batch_data_old`.`BusinessPartner`"},
	Product:                   whereHelperstring{field: "`data_platform_product_stock_by_batch_data_old`.`Product`"},
	Plant:                     whereHelperstring{field: "`data_platform_product_stock_by_batch_data_old`.`Plant`"},
	Batch:                     whereHelperstring{field: "`data_platform_product_stock_by_batch_data_old`.`Batch`"},
	InventoryStockType:        whereHelpernull_String{field: "`data_platform_product_stock_by_batch_data_old`.`InventoryStockType`"},
	InventorySpecialStockType: whereHelpernull_String{field: "`data_platform_product_stock_by_batch_data_old`.`InventorySpecialStockType`"},
	ProductStock:              whereHelperfloat32{field: "`data_platform_product_stock_by_batch_data_old`.`ProductStock`"},
}

// DataPlatformProductStockByBatchDataOldRels is where relationship names are stored.
var DataPlatformProductStockByBatchDataOldRels = struct {
	BusinessPartnerDataPlatformProductStockProductStockDataOld string
}{
	BusinessPartnerDataPlatformProductStockProductStockDataOld: "BusinessPartnerDataPlatformProductStockProductStockDataOld",
}

// dataPlatformProductStockByBatchDataOldR is where relationships are stored.
type dataPlatformProductStockByBatchDataOldR struct {
	BusinessPartnerDataPlatformProductStockProductStockDataOld *DataPlatformProductStockProductStockDataOld `boil:"BusinessPartnerDataPlatformProductStockProductStockDataOld" json:"BusinessPartnerDataPlatformProductStockProductStockDataOld" toml:"BusinessPartnerDataPlatformProductStockProductStockDataOld" yaml:"BusinessPartnerDataPlatformProductStockProductStockDataOld"`
}

// NewStruct creates a new relationship struct
func (*dataPlatformProductStockByBatchDataOldR) NewStruct() *dataPlatformProductStockByBatchDataOldR {
	return &dataPlatformProductStockByBatchDataOldR{}
}

func (r *dataPlatformProductStockByBatchDataOldR) GetBusinessPartnerDataPlatformProductStockProductStockDataOld() *DataPlatformProductStockProductStockDataOld {
	if r == nil {
		return nil
	}
	return r.BusinessPartnerDataPlatformProductStockProductStockDataOld
}

// dataPlatformProductStockByBatchDataOldL is where Load methods for each relationship are stored.
type dataPlatformProductStockByBatchDataOldL struct{}

var (
	dataPlatformProductStockByBatchDataOldAllColumns            = []string{"BusinessPartner", "Product", "Plant", "Batch", "InventoryStockType", "InventorySpecialStockType", "ProductStock"}
	dataPlatformProductStockByBatchDataOldColumnsWithoutDefault = []string{"BusinessPartner", "Product", "Plant", "Batch", "InventoryStockType", "InventorySpecialStockType", "ProductStock"}
	dataPlatformProductStockByBatchDataOldColumnsWithDefault    = []string{}
	dataPlatformProductStockByBatchDataOldPrimaryKeyColumns     = []string{"BusinessPartner", "Product", "Plant", "Batch"}
	dataPlatformProductStockByBatchDataOldGeneratedColumns      = []string{}
)

type (
	// DataPlatformProductStockByBatchDataOldSlice is an alias for a slice of pointers to DataPlatformProductStockByBatchDataOld.
	// This should almost always be used instead of []DataPlatformProductStockByBatchDataOld.
	DataPlatformProductStockByBatchDataOldSlice []*DataPlatformProductStockByBatchDataOld

	dataPlatformProductStockByBatchDataOldQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	dataPlatformProductStockByBatchDataOldType                 = reflect.TypeOf(&DataPlatformProductStockByBatchDataOld{})
	dataPlatformProductStockByBatchDataOldMapping              = queries.MakeStructMapping(dataPlatformProductStockByBatchDataOldType)
	dataPlatformProductStockByBatchDataOldPrimaryKeyMapping, _ = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns)
	dataPlatformProductStockByBatchDataOldInsertCacheMut       sync.RWMutex
	dataPlatformProductStockByBatchDataOldInsertCache          = make(map[string]insertCache)
	dataPlatformProductStockByBatchDataOldUpdateCacheMut       sync.RWMutex
	dataPlatformProductStockByBatchDataOldUpdateCache          = make(map[string]updateCache)
	dataPlatformProductStockByBatchDataOldUpsertCacheMut       sync.RWMutex
	dataPlatformProductStockByBatchDataOldUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single dataPlatformProductStockByBatchDataOld record from the query.
func (q dataPlatformProductStockByBatchDataOldQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DataPlatformProductStockByBatchDataOld, error) {
	o := &DataPlatformProductStockByBatchDataOld{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for data_platform_product_stock_by_batch_data_old")
	}

	return o, nil
}

// All returns all DataPlatformProductStockByBatchDataOld records from the query.
func (q dataPlatformProductStockByBatchDataOldQuery) All(ctx context.Context, exec boil.ContextExecutor) (DataPlatformProductStockByBatchDataOldSlice, error) {
	var o []*DataPlatformProductStockByBatchDataOld

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DataPlatformProductStockByBatchDataOld slice")
	}

	return o, nil
}

// Count returns the count of all DataPlatformProductStockByBatchDataOld records in the query.
func (q dataPlatformProductStockByBatchDataOldQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count data_platform_product_stock_by_batch_data_old rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q dataPlatformProductStockByBatchDataOldQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if data_platform_product_stock_by_batch_data_old exists")
	}

	return count > 0, nil
}

// BusinessPartnerDataPlatformProductStockProductStockDataOld pointed to by the foreign key.
func (o *DataPlatformProductStockByBatchDataOld) BusinessPartnerDataPlatformProductStockProductStockDataOld(mods ...qm.QueryMod) dataPlatformProductStockProductStockDataOldQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`BusinessPartner` = ?", o.BusinessPartner),
	}

	queryMods = append(queryMods, mods...)

	return DataPlatformProductStockProductStockDataOlds(queryMods...)
}

// LoadBusinessPartnerDataPlatformProductStockProductStockDataOld allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (dataPlatformProductStockByBatchDataOldL) LoadBusinessPartnerDataPlatformProductStockProductStockDataOld(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDataPlatformProductStockByBatchDataOld interface{}, mods queries.Applicator) error {
	var slice []*DataPlatformProductStockByBatchDataOld
	var object *DataPlatformProductStockByBatchDataOld

	if singular {
		var ok bool
		object, ok = maybeDataPlatformProductStockByBatchDataOld.(*DataPlatformProductStockByBatchDataOld)
		if !ok {
			object = new(DataPlatformProductStockByBatchDataOld)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDataPlatformProductStockByBatchDataOld)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDataPlatformProductStockByBatchDataOld))
			}
		}
	} else {
		s, ok := maybeDataPlatformProductStockByBatchDataOld.(*[]*DataPlatformProductStockByBatchDataOld)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDataPlatformProductStockByBatchDataOld)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDataPlatformProductStockByBatchDataOld))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &dataPlatformProductStockByBatchDataOldR{}
		}
		args = append(args, object.BusinessPartner)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &dataPlatformProductStockByBatchDataOldR{}
			}

			for _, a := range args {
				if a == obj.BusinessPartner {
					continue Outer
				}
			}

			args = append(args, obj.BusinessPartner)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`data_platform_product_stock_product_stock_data_old`),
		qm.WhereIn(`data_platform_product_stock_product_stock_data_old.BusinessPartner in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load DataPlatformProductStockProductStockDataOld")
	}

	var resultSlice []*DataPlatformProductStockProductStockDataOld
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice DataPlatformProductStockProductStockDataOld")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for data_platform_product_stock_product_stock_data_old")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for data_platform_product_stock_product_stock_data_old")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.BusinessPartnerDataPlatformProductStockProductStockDataOld = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BusinessPartner == foreign.BusinessPartner {
				local.R.BusinessPartnerDataPlatformProductStockProductStockDataOld = foreign
				break
			}
		}
	}

	return nil
}

// SetBusinessPartnerDataPlatformProductStockProductStockDataOld of the dataPlatformProductStockByBatchDataOld to the related item.
// Sets o.R.BusinessPartnerDataPlatformProductStockProductStockDataOld to related.
func (o *DataPlatformProductStockByBatchDataOld) SetBusinessPartnerDataPlatformProductStockProductStockDataOld(ctx context.Context, exec boil.ContextExecutor, insert bool, related *DataPlatformProductStockProductStockDataOld) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `data_platform_product_stock_by_batch_data_old` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"BusinessPartner"}),
		strmangle.WhereClause("`", "`", 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns),
	)
	values := []interface{}{related.BusinessPartner, o.BusinessPartner, o.Product, o.Plant, o.Batch}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BusinessPartner = related.BusinessPartner
	if o.R == nil {
		o.R = &dataPlatformProductStockByBatchDataOldR{
			BusinessPartnerDataPlatformProductStockProductStockDataOld: related,
		}
	} else {
		o.R.BusinessPartnerDataPlatformProductStockProductStockDataOld = related
	}

	return nil
}

// DataPlatformProductStockByBatchDataOlds retrieves all the records using an executor.
func DataPlatformProductStockByBatchDataOlds(mods ...qm.QueryMod) dataPlatformProductStockByBatchDataOldQuery {
	mods = append(mods, qm.From("`data_platform_product_stock_by_batch_data_old`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`data_platform_product_stock_by_batch_data_old`.*"})
	}

	return dataPlatformProductStockByBatchDataOldQuery{q}
}

// FindDataPlatformProductStockByBatchDataOld retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDataPlatformProductStockByBatchDataOld(ctx context.Context, exec boil.ContextExecutor, businessPartner int, product string, plant string, batch string, selectCols ...string) (*DataPlatformProductStockByBatchDataOld, error) {
	dataPlatformProductStockByBatchDataOldObj := &DataPlatformProductStockByBatchDataOld{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `data_platform_product_stock_by_batch_data_old` where `BusinessPartner`=? AND `Product`=? AND `Plant`=? AND `Batch`=?", sel,
	)

	q := queries.Raw(query, businessPartner, product, plant, batch)

	err := q.Bind(ctx, exec, dataPlatformProductStockByBatchDataOldObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from data_platform_product_stock_by_batch_data_old")
	}

	return dataPlatformProductStockByBatchDataOldObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DataPlatformProductStockByBatchDataOld) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no data_platform_product_stock_by_batch_data_old provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(dataPlatformProductStockByBatchDataOldColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	dataPlatformProductStockByBatchDataOldInsertCacheMut.RLock()
	cache, cached := dataPlatformProductStockByBatchDataOldInsertCache[key]
	dataPlatformProductStockByBatchDataOldInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			dataPlatformProductStockByBatchDataOldAllColumns,
			dataPlatformProductStockByBatchDataOldColumnsWithDefault,
			dataPlatformProductStockByBatchDataOldColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `data_platform_product_stock_by_batch_data_old` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `data_platform_product_stock_by_batch_data_old` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `data_platform_product_stock_by_batch_data_old` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into data_platform_product_stock_by_batch_data_old")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.BusinessPartner,
		o.Product,
		o.Plant,
		o.Batch,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for data_platform_product_stock_by_batch_data_old")
	}

CacheNoHooks:
	if !cached {
		dataPlatformProductStockByBatchDataOldInsertCacheMut.Lock()
		dataPlatformProductStockByBatchDataOldInsertCache[key] = cache
		dataPlatformProductStockByBatchDataOldInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DataPlatformProductStockByBatchDataOld.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DataPlatformProductStockByBatchDataOld) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	var err error
	key := makeCacheKey(columns, nil)
	dataPlatformProductStockByBatchDataOldUpdateCacheMut.RLock()
	cache, cached := dataPlatformProductStockByBatchDataOldUpdateCache[key]
	dataPlatformProductStockByBatchDataOldUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			dataPlatformProductStockByBatchDataOldAllColumns,
			dataPlatformProductStockByBatchDataOldPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update data_platform_product_stock_by_batch_data_old, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `data_platform_product_stock_by_batch_data_old` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, append(wl, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update data_platform_product_stock_by_batch_data_old row")
	}

	if !cached {
		dataPlatformProductStockByBatchDataOldUpdateCacheMut.Lock()
		dataPlatformProductStockByBatchDataOldUpdateCache[key] = cache
		dataPlatformProductStockByBatchDataOldUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q dataPlatformProductStockByBatchDataOldQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for data_platform_product_stock_by_batch_data_old")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DataPlatformProductStockByBatchDataOldSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformProductStockByBatchDataOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `data_platform_product_stock_by_batch_data_old` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in dataPlatformProductStockByBatchDataOld slice")
	}

	return nil
}

var mySQLDataPlatformProductStockByBatchDataOldUniqueColumns = []string{}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DataPlatformProductStockByBatchDataOld) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no data_platform_product_stock_by_batch_data_old provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(dataPlatformProductStockByBatchDataOldColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLDataPlatformProductStockByBatchDataOldUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	dataPlatformProductStockByBatchDataOldUpsertCacheMut.RLock()
	cache, cached := dataPlatformProductStockByBatchDataOldUpsertCache[key]
	dataPlatformProductStockByBatchDataOldUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			dataPlatformProductStockByBatchDataOldAllColumns,
			dataPlatformProductStockByBatchDataOldColumnsWithDefault,
			dataPlatformProductStockByBatchDataOldColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			dataPlatformProductStockByBatchDataOldAllColumns,
			dataPlatformProductStockByBatchDataOldPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert data_platform_product_stock_by_batch_data_old, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`data_platform_product_stock_by_batch_data_old`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `data_platform_product_stock_by_batch_data_old` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for data_platform_product_stock_by_batch_data_old")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(dataPlatformProductStockByBatchDataOldType, dataPlatformProductStockByBatchDataOldMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for data_platform_product_stock_by_batch_data_old")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for data_platform_product_stock_by_batch_data_old")
	}

CacheNoHooks:
	if !cached {
		dataPlatformProductStockByBatchDataOldUpsertCacheMut.Lock()
		dataPlatformProductStockByBatchDataOldUpsertCache[key] = cache
		dataPlatformProductStockByBatchDataOldUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DataPlatformProductStockByBatchDataOld record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DataPlatformProductStockByBatchDataOld) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no DataPlatformProductStockByBatchDataOld provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), dataPlatformProductStockByBatchDataOldPrimaryKeyMapping)
	sql := "DELETE FROM `data_platform_product_stock_by_batch_data_old` WHERE `BusinessPartner`=? AND `Product`=? AND `Plant`=? AND `Batch`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from data_platform_product_stock_by_batch_data_old")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q dataPlatformProductStockByBatchDataOldQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no dataPlatformProductStockByBatchDataOldQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from data_platform_product_stock_by_batch_data_old")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DataPlatformProductStockByBatchDataOldSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformProductStockByBatchDataOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `data_platform_product_stock_by_batch_data_old` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from dataPlatformProductStockByBatchDataOld slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DataPlatformProductStockByBatchDataOld) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDataPlatformProductStockByBatchDataOld(ctx, exec, o.BusinessPartner, o.Product, o.Plant, o.Batch)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DataPlatformProductStockByBatchDataOldSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DataPlatformProductStockByBatchDataOldSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), dataPlatformProductStockByBatchDataOldPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `data_platform_product_stock_by_batch_data_old`.* FROM `data_platform_product_stock_by_batch_data_old` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, dataPlatformProductStockByBatchDataOldPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DataPlatformProductStockByBatchDataOldSlice")
	}

	*o = slice

	return nil
}

// DataPlatformProductStockByBatchDataOldExists checks if the DataPlatformProductStockByBatchDataOld row exists.
func DataPlatformProductStockByBatchDataOldExists(ctx context.Context, exec boil.ContextExecutor, businessPartner int, product string, plant string, batch string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `data_platform_product_stock_by_batch_data_old` where `BusinessPartner`=? AND `Product`=? AND `Plant`=? AND `Batch`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, businessPartner, product, plant, batch)
	}
	row := exec.QueryRowContext(ctx, sql, businessPartner, product, plant, batch)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if data_platform_product_stock_by_batch_data_old exists")
	}

	return exists, nil
}

// Exists checks if the DataPlatformProductStockByBatchDataOld row exists.
func (o *DataPlatformProductStockByBatchDataOld) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DataPlatformProductStockByBatchDataOldExists(ctx, exec, o.BusinessPartner, o.Product, o.Plant, o.Batch)
}
